version: "3"
services:
  db:
    container_name: employee_database
    image: employee_db_img
    environment:
      MYSQL_ROOT_PASSWORD: "0123456789"
      MYSQL_DATABASE: "employee_db"      
    ports:
      - "3306:3306"
    volumes:
      - "mysql_vol:/var/lib/mysql"
  employeews:
    container_name: employee_soap_app
    image: employee_soap_ws
    depends_on:
      - db
    ports:
      - "10002:10002"
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/employee_db"      

  employee_rest:
    container_name: employee_rest_api_app
    image: employee_rest_api
    depends_on:
      - employeews
    environment:
      SOAP_CLIENT_URL: "employeews:10002"
    ports:
      - "10001:10001"      
volumes:
  mysql_vol:
